// <auto-generated />
using System;
using HR28.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR28.Infrastructure.Migrations
{
    [DbContext(typeof(HR28DbContext))]
    [Migration("20261007032836_AddTrustedDevices")]
    partial class AddTrustedDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");
                });

            modelBuilder.Entity("HR28.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HR28.Domain.Entities.AuthorizationCodeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizationCodeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthorizationCodeHistories");
                });

            modelBuilder.Entity("HR28.Domain.Entities.ConstituencyIsland", b =>
                {
                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IslandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConstituencyId", "IslandId");

                    b.HasIndex("IslandId");

                    b.ToTable("ConstituencyIslands");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EncounterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncounterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("VoterId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Influencer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IslandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("IslandId");

                    b.ToTable("Influencers");
                });

            modelBuilder.Entity("HR28.Domain.Entities.InfluencerCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InfluencerCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a10-0b5e-4d39-9a51-1c0e7a3d5001"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MP",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("6f1c2a10-0b5e-4d39-9a51-1c0e7a3d5002"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Island Council",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("6f1c2a10-0b5e-4d39-9a51-1c0e7a3d5003"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GM Member",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("HR28.Domain.Entities.Island", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Atoll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Islands");
                });

            modelBuilder.Entity("HR28.Domain.Entities.OtpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpRequests");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Pledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FulfilledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PledgeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("VoterId");

                    b.ToTable("Pledges");
                });

            modelBuilder.Entity("HR28.Domain.Entities.PoliticalParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefaultFilter")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PoliticalParties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7001"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = true,
                            Name = "Maldivian Democratic Party",
                            ShortName = "MDP",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7002"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = false,
                            Name = "People's National Congress",
                            ShortName = "PNC",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7003"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = false,
                            Name = "Jumhooree Party",
                            ShortName = "JP",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7004"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = false,
                            Name = "Maldives Development Alliance",
                            ShortName = "MDA",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7005"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = false,
                            Name = "Adhaalath Party",
                            ShortName = "AP",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7006"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = false,
                            Name = "Maldives National Party",
                            ShortName = "MNP",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("8a3e5c20-4f1d-4b7a-9c2e-5d0f6b1a7007"),
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefaultFilter = false,
                            Name = "People's National Front",
                            ShortName = "PNF",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("HR28.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Dashboard");

                    b.Property<string>("VoterProfileView")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Full");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HR28.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("HR28.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("HR28.Domain.Entities.TrustedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TrustedDevices");
                });

            modelBuilder.Entity("HR28.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizationCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationCodeHash")
                        .IsUnique()
                        .HasFilter("[AuthorizationCodeHash] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HR28.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "Permission");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("HR28.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HR28.Domain.Entities.UserScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IslandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("IslandId");

                    b.HasIndex("UserId");

                    b.ToTable("UserScopes");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtollCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConstituencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstituencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IslandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("PoliticalPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegisteredIsland")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtollCode");

                    b.HasIndex("ConstituencyCode");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("IslandId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("RegisteredIsland");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("HR28.Domain.Entities.VoterInfluencer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InfluencerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InfluencerId");

                    b.HasIndex("VoterId", "InfluencerId")
                        .IsUnique();

                    b.ToTable("VoterInfluencers");
                });

            modelBuilder.Entity("HR28.Domain.Entities.VoterPhoto", b =>
                {
                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VoterId");

                    b.ToTable("VoterPhotos");
                });

            modelBuilder.Entity("HR28.Domain.Entities.AuthorizationCodeHistory", b =>
                {
                    b.HasOne("HR28.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR28.Domain.Entities.ConstituencyIsland", b =>
                {
                    b.HasOne("Constituency", "Constituency")
                        .WithMany("ConstituencyIslands")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.Island", "Island")
                        .WithMany("ConstituencyIslands")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Island");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("HR28.Domain.Entities.User", "RecordedByUser")
                        .WithMany("RecordedEncounters")
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.Voter", "Voter")
                        .WithMany("Encounters")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Influencer", b =>
                {
                    b.HasOne("HR28.Domain.Entities.InfluencerCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.Island", "Island")
                        .WithMany()
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Constituency");

                    b.Navigation("Island");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Island", b =>
                {
                    b.HasOne("Constituency", "Constituency")
                        .WithMany("Islands")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("HR28.Domain.Entities.OtpRequest", b =>
                {
                    b.HasOne("HR28.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Pledge", b =>
                {
                    b.HasOne("HR28.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedPledges")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HR28.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedPledges")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.Voter", "Voter")
                        .WithMany("Pledges")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("HR28.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("HR28.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HR28.Domain.Entities.TrustedDevice", b =>
                {
                    b.HasOne("HR28.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR28.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("HR28.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR28.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HR28.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR28.Domain.Entities.UserScope", b =>
                {
                    b.HasOne("Constituency", "Constituency")
                        .WithMany("UserScopes")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HR28.Domain.Entities.Island", "Island")
                        .WithMany("UserScopes")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HR28.Domain.Entities.User", "User")
                        .WithMany("UserScopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Island");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Voter", b =>
                {
                    b.HasOne("Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.Island", "Island")
                        .WithMany()
                        .HasForeignKey("IslandId");

                    b.HasOne("HR28.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Constituency");

                    b.Navigation("Island");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("HR28.Domain.Entities.VoterInfluencer", b =>
                {
                    b.HasOne("HR28.Domain.Entities.Influencer", "Influencer")
                        .WithMany("Voters")
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HR28.Domain.Entities.Voter", "Voter")
                        .WithMany("Influencers")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Influencer");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("HR28.Domain.Entities.VoterPhoto", b =>
                {
                    b.HasOne("HR28.Domain.Entities.Voter", "Voter")
                        .WithOne()
                        .HasForeignKey("HR28.Domain.Entities.VoterPhoto", "VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Constituency", b =>
                {
                    b.Navigation("ConstituencyIslands");

                    b.Navigation("Islands");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Influencer", b =>
                {
                    b.Navigation("Voters");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Island", b =>
                {
                    b.Navigation("ConstituencyIslands");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HR28.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedPledges");

                    b.Navigation("CreatedPledges");

                    b.Navigation("RecordedEncounters");

                    b.Navigation("UserRoles");

                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("HR28.Domain.Entities.Voter", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("Influencers");

                    b.Navigation("Pledges");
                });
#pragma warning restore 612, 618
        }
    }
}
